//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlarmMaster()
        {
            this.AlarmUpdates = new HashSet<AlarmUpdate>();
        }
    
        public string CN { get; set; }
        public string AlarmID { get; set; }
        public int FactoryID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public int RenewalFreq { get; set; }
        public string RenewalFreqUnit { get; set; }
        public System.DateTime RenewalDueDate { get; set; }
        public int AlarmDays { get; set; }
        public int AlarmFreq { get; set; }
        public System.DateTime NextAlarmDate { get; set; }
        public Nullable<int> AlarmToGroupID { get; set; }
        public bool RequireMail { get; set; }
        public string AlarmMemo { get; set; }
        public System.DateTime EstablishDate { get; set; }
        public string EstablishPeople { get; set; }
        public int ItemState { get; set; }
    
        public virtual AlarmCategory AlarmCategory { get; set; }
        public virtual FactoryMaster FactoryMaster { get; set; }
        public virtual PeopleGroup PeopleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmUpdate> AlarmUpdates { get; set; }
    }
}
