//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentMaster
    {
        public long ContentId { get; set; }
        public string CN { get; set; }
        public bool ShowContent { get; set; }
        public Nullable<System.DateTime> DisplayStartDate { get; set; }
        public Nullable<System.DateTime> DisplayEndDate { get; set; }
        public Nullable<bool> ShowMarquee { get; set; }
        public Nullable<System.DateTime> MarqueeStartDate { get; set; }
        public Nullable<System.DateTime> MarqueeEndDate { get; set; }
        public Nullable<bool> ShowHotIcon { get; set; }
        public Nullable<System.DateTime> HotIconStartDate { get; set; }
        public Nullable<System.DateTime> HotIconEndDate { get; set; }
        public bool FixTop { get; set; }
        public int OrderNumber { get; set; }
        public int ContentType { get; set; }
        public int PageView { get; set; }
        public string Language { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
