//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESHCloudsEntities : DbContext
    {
        public ESHCloudsEntities()
            : base("name=ESHCloudsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmCategory> AlarmCategories { get; set; }
        public virtual DbSet<AlarmMaster> AlarmMasters { get; set; }
        public virtual DbSet<AlarmUpdate> AlarmUpdates { get; set; }
        public virtual DbSet<ContentMaster> ContentMasters { get; set; }
        public virtual DbSet<DepartData> DepartDatas { get; set; }
        public virtual DbSet<FactoryMaster> FactoryMasters { get; set; }
        public virtual DbSet<FileMaster> FileMasters { get; set; }
        public virtual DbSet<GroupDetail> GroupDetails { get; set; }
        public virtual DbSet<LogMaster> LogMasters { get; set; }
        public virtual DbSet<MailLog> MailLogs { get; set; }
        public virtual DbSet<PeopleData> PeopleDatas { get; set; }
        public virtual DbSet<PeopleGroup> PeopleGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int sp_CleatTestData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CleatTestData");
        }
    
        public virtual ObjectResult<string> sp_GetAlarmMasterId(string cN)
        {
            var cNParameter = cN != null ?
                new ObjectParameter("CN", cN) :
                new ObjectParameter("CN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetAlarmMasterId", cNParameter);
        }
    }
}
