//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactoryMaster()
        {
            this.AlarmMasters = new HashSet<AlarmMaster>();
            this.DepartDatas = new HashSet<DepartData>();
        }
    
        public string CN { get; set; }
        public int FactoryID { get; set; }
        public string FactoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmMaster> AlarmMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartData> DepartDatas { get; set; }
    }
}
