//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMaster
    {
        public string CN { get; set; }
        public string ListID { get; set; }
        public string SystemName { get; set; }
        public string ModifyType { get; set; }
        public string ModifyDescription { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyPeople { get; set; }
    }
}
