//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleData
    {
        public string CN { get; set; }
        public int FactoryID { get; set; }
        public int DepartID { get; set; }
        public string PeopleID { get; set; }
        public string Pasd { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
    
        public virtual DepartData DepartData { get; set; }
    }
}
