//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHCloudsWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeopleGroup()
        {
            this.AlarmMasters = new HashSet<AlarmMaster>();
            this.GroupDetails = new HashSet<GroupDetail>();
        }
    
        public string CN { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public int GroupOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmMaster> AlarmMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupDetail> GroupDetails { get; set; }
    }
}
